# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ac1088d748ab262c2ffa6e683921c9a05c6f5d12da2957a0e567c9a4a5c5aa94a55b4b66faf6891a037a60bd17a5211e0c0d6bd6ee1236d8ff77b4ec5c24044

test:
  secret_key_base: 5efd4de0e5a831addd93273f7cdb959a92439bc366a59f0a362b078f227ad6ac8a6cfc46647268c80a8fd25031d34273b1c9685a5241abe645ad710d1a570c8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
